runtime: python312

instance_class: F1

handlers:
  # Serve all static files with `/dist` prefix
  - url: /assets
    static_dir: dist/assets
    secure: always
    expiration: "30d"

  - url: /(.+)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always

  # Catch all handler to index.html (SPA fallback)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
